# Generated by Django 4.0.6 on 2022-07-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pet'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='Pet',
        ),
    ]
