# Generated by Django 4.0.6 on 2022-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pet_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(verbose_name='Tuổi'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Màu Sắc'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã Thú Cưng'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='length',
            field=models.IntegerField(verbose_name='Chiều Dài'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Tên Thú Cưng'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(verbose_name='Cân Nặng'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
